import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Subscription, timer } from 'rxjs';
import { AutomationService } from '../core/automation.service';
import { ShellComponent } from '../shared/shell.component';

@Component({selector:'sn-automation-monitor',standalone:true,imports:[CommonModule,FormsModule,ShellComponent],template:`<sn-shell title="Automation Monitor">
<section class="hero"><div><div class="eyebrow">Runtime operations</div><h2>Automation execution center</h2><p>Watch live runs, investigate failures and safely retry failed workflows.</p></div><button (click)="refresh()">Refresh</button></section>
<div class="notice" *ngIf="error">{{error}}</div>
<section class="cards"><article><span>Enabled rules</span><b>{{summary?.active_rules||0}}</b></article><article><span>Queued</span><b>{{summary?.queued||0}}</b></article><article><span>Succeeded · 24h</span><b>{{summary?.succeeded||0}}</b></article><article><span>Failed · 24h</span><b>{{summary?.failed||0}}</b></article><article><span>Success rate</span><b>{{summary?.success_rate||0}}%</b></article></section>
<section class="panel"><div class="head"><h3>Recent executions</h3><label>Status<select [(ngModel)]="filter" (change)="loadRuns()"><option value="">All</option><option value="queued">Queued</option><option value="succeeded">Succeeded</option><option value="partial">Partial</option><option value="failed">Failed</option></select></label></div>
<div class="table"><div class="tr header"><span>Started</span><span>Rule</span><span>Event</span><span>Status</span><span>Attempts</span><span>Action</span></div><div class="tr" *ngFor="let r of runs"><span>{{r.started_at|date:'medium'}}</span><span><b>{{r.rule_name}}</b><small>{{r.id}}</small></span><span>{{r.event_type||'manual'}}</span><span><em [class.ok]="r.status==='succeeded'" [class.bad]="r.status==='failed'">{{r.status}}</em><small *ngIf="r.error">{{r.error}}</small></span><span>{{r.attempt_count}}</span><span><button *ngIf="r.status==='failed'||r.status==='partial'" (click)="retry(r)" [disabled]="busy===r.id">{{busy===r.id?'Queueing…':'Retry'}}</button></span></div></div><div class="empty" *ngIf="!runs.length">No executions found.</div></section>
</sn-shell>`,styles:[`.hero,.panel,.cards article{border:1px solid var(--line);background:rgba(16,22,38,.72);border-radius:18px}.hero{padding:1.3rem;display:flex;justify-content:space-between;align-items:center;gap:1rem}.eyebrow{color:var(--primary);text-transform:uppercase;letter-spacing:.12em;font-size:.72rem}.hero h2{margin:.2rem 0}.hero p,span,small{color:var(--muted)}button,select{padding:.65rem .9rem;border-radius:10px;background:var(--primary-soft);color:var(--text);border:1px solid var(--line)}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:.8rem;margin:1rem 0}.cards article{padding:1rem;display:grid;gap:.5rem}.cards b{font-size:1.8rem}.panel{padding:1rem}.head{display:flex;justify-content:space-between;align-items:center}.head label{display:flex;gap:.5rem;align-items:center}.table{display:grid;margin-top:1rem}.tr{display:grid;grid-template-columns:1.2fr 1.4fr 1fr 1.2fr .6fr .7fr;gap:.8rem;padding:.8rem;border-top:1px solid var(--line);align-items:center}.tr span{display:grid;gap:.25rem;min-width:0}.header{font-size:.72rem;text-transform:uppercase;letter-spacing:.08em}.tr em{font-style:normal;color:#ffd08a;text-transform:uppercase}.tr em.ok{color:#74e9b3}.tr em.bad,.notice{color:#ff91a5}.tr small{overflow:hidden;text-overflow:ellipsis}.empty{padding:2rem;text-align:center;color:var(--muted)}@media(max-width:1000px){.cards{grid-template-columns:repeat(2,1fr)}.table{overflow:auto}.tr{min-width:900px}.hero{align-items:flex-start;flex-direction:column}}`]})
export class AutomationMonitorComponent implements OnInit,OnDestroy{guildId='';summary:any={};runs:any[]=[];filter='';error='';busy='';sub?:Subscription;constructor(private api:AutomationService,private route:ActivatedRoute){}ngOnInit(){this.guildId=this.route.snapshot.paramMap.get('guildId') ?? '';this.refresh();this.sub=timer(15000,15000).subscribe(()=>this.refresh())}ngOnDestroy(){this.sub?.unsubscribe()}refresh(){this.api.monitorSummary(this.guildId).subscribe({next:v=>this.summary=v,error:e=>this.error=e?.error?.detail||'Unable to load monitor summary.'});this.loadRuns()}loadRuns(){this.api.monitorRuns(this.guildId,this.filter).subscribe({next:v=>this.runs=v,error:e=>this.error=e?.error?.detail||'Unable to load automation runs.'})}retry(r:any){this.busy=r.id;this.api.retryRun(this.guildId,r.id).subscribe({next:()=>{this.busy='';this.refresh()},error:e=>{this.busy='';this.error=e?.error?.detail||'Unable to retry run.'}})}}
