import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { BackupService, GuildBackup } from '../core/backup.service';
import { ShellComponent } from '../shared/shell.component';
@Component({selector:'sn-backups',standalone:true,imports:[CommonModule,FormsModule,ShellComponent],template:`<sn-shell title="Backup Center">
<section class="hero"><div><div class="eyebrow">Discord configuration protection</div><h2>Server backups</h2><p>Create versioned JSON snapshots of roles, channels, overwrites, modules and verification settings.</p></div><button (click)="create()" [disabled]="loading||!name.trim()">{{loading?'Creating…':'Create backup'}}</button></section>
<section class="create"><label>Name<input [(ngModel)]="name" placeholder="Before permissions update"></label><label>Description<input [(ngModel)]="description" placeholder="Optional note"></label></section>
<div class="notice err" *ngIf="error">{{error}}</div>
<section class="grid">
<article *ngFor="let item of items"><header><div><b>{{item.name}}</b><span>{{item.created_at|date:'medium'}}</span></div><em>{{format(item.size_bytes)}}</em></header><p>{{item.description||'No description'}}</p><div class="stats"><span>{{item.object_count}} objects</span><span>Format v{{item.format_version}}</span><span>{{item.status}}</span></div><footer><button (click)="download(item)">Download JSON</button><button (click)="plan(item)">Dry-run restore</button><button class="danger" (click)="remove(item)">Delete</button></footer></article>
<div class="empty" *ngIf="!loading&&items.length===0">No backups yet.</div></section>
<section class="plan" *ngIf="restorePlan"><div class="plan-head"><h3>Restore plan</h3><button (click)="restorePlan=null">Close</button></div><div class="warn">{{restorePlan.message}}</div><div class="rows"><div *ngFor="let row of restorePlan.sections"><b>{{row.section}}</b><span>Current {{row.current}}</span><span>Backup {{row.backup}}</span><em [class.pos]="row.delta>0">{{row.delta>0?'+':''}}{{row.delta}}</em></div></div><ul><li *ngFor="let warning of restorePlan.warnings">{{warning}}</li></ul></section>
</sn-shell>`,styles:[`.hero,.create,.grid article,.plan{border:1px solid var(--line);background:rgba(16,22,38,.72);border-radius:18px}.hero{padding:1.3rem;display:flex;justify-content:space-between;align-items:center}.hero h2{margin:.2rem 0}.hero p,.create label,article span,article p{color:var(--muted)}.eyebrow{color:var(--primary);text-transform:uppercase;letter-spacing:.12em;font-size:.72rem}.hero button,.create button,footer button,footer a{padding:.7rem 1rem;border-radius:10px;background:var(--primary);color:#fff}.create{display:grid;grid-template-columns:1fr 2fr;gap:1rem;padding:1rem;margin:1rem 0}.create label{display:grid;gap:.4rem}input{background:#0c1323;color:var(--text);border:1px solid var(--line);padding:.8rem;border-radius:10px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.grid article{padding:1rem}.grid header{display:flex;justify-content:space-between;gap:1rem}.grid header div{display:grid;gap:.25rem}.grid em{font-style:normal;color:#9fd6ff}.stats{display:flex;gap:.5rem;flex-wrap:wrap;margin:1rem 0}.stats span{border:1px solid var(--line);padding:.3rem .5rem;border-radius:8px}footer{display:flex;gap:.5rem;flex-wrap:wrap}footer button,footer a{background:var(--primary-soft);border:1px solid var(--line)}footer .danger{color:#ff91a5}.plan{margin-top:1rem;padding:1rem}.plan-head{display:flex;justify-content:space-between}.warn{padding:.8rem;background:rgba(255,183,77,.12);border-radius:10px;color:#ffd08a}.rows div{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:1rem;padding:.7rem;border-bottom:1px solid var(--line)}.rows span,li{color:var(--muted)}.rows em{color:#ff91a5}.rows em.pos{color:#74e9b3}.empty,.notice{padding:1rem}.err{color:#ff91a5}@media(max-width:800px){.grid,.create{grid-template-columns:1fr}.hero{align-items:flex-start;gap:1rem;flex-direction:column}}` ]})
export class BackupsComponent implements OnInit{guildId='';items:GuildBackup[]=[];name='Manual backup';description='';loading=false;error='';restorePlan:any=null;constructor(public api:BackupService,private route:ActivatedRoute){}ngOnInit(){this.guildId=this.route.snapshot.paramMap.get('guildId') ?? '';this.load()}load(){this.api.list(this.guildId).subscribe({next:v=>this.items=v,error:e=>this.error=e?.error?.detail||'Unable to load backups.'})}create(){this.loading=true;this.error='';this.api.create(this.guildId,{name:this.name,description:this.description||undefined}).subscribe({next:()=>{this.loading=false;this.load()},error:e=>{this.loading=false;this.error=e?.error?.detail||'Unable to create backup.'}})}plan(x:GuildBackup){this.api.plan(this.guildId,x.id).subscribe({next:v=>this.restorePlan=v,error:e=>this.error=e?.error?.detail||'Unable to build restore plan.'})}download(x:GuildBackup){this.api.download(this.guildId,x.id).subscribe({next:blob=>{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`shieldnet-guild-${this.guildId}-${x.id}.json`;a.click();URL.revokeObjectURL(url)},error:e=>this.error=e?.error?.detail||'Unable to download backup.'})}remove(x:GuildBackup){if(!confirm(`Delete backup ${x.name}?`))return;this.api.remove(this.guildId,x.id).subscribe({next:()=>this.load(),error:e=>this.error=e?.error?.detail||'Unable to delete backup.'})}format(n:number){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}}
