"""Plugin permissions, secrets, activation and package history.
Revision ID: 8d5fb9400048
Revises: 7c4fa8300047
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = "8d5fb9400048"; down_revision = "7c4fa8300047"; branch_labels = None; depends_on = None

def upgrade():
    op.create_table("permissions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("permission_key", sa.String(120), nullable=False), sa.Column("description", sa.Text()), sa.Column("risk_level", sa.String(16), nullable=False, server_default="low"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("permission_key", name="uq_plugins_permissions_key"), schema="plugins")
    op.create_table("plugin_permissions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("plugin_key", sa.String(96), nullable=False), sa.Column("permission_key", sa.String(120), nullable=False), sa.Column("granted", sa.Boolean(), nullable=False, server_default="false"), sa.Column("granted_by_user_id", postgresql.UUID(as_uuid=True)), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("plugin_key", "permission_key", name="uq_plugins_plugin_permission"), schema="plugins")
    op.create_table("permission_audit", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("plugin_key", sa.String(96), nullable=False), sa.Column("permission_key", sa.String(120), nullable=False), sa.Column("action", sa.String(32), nullable=False), sa.Column("actor_user_id", postgresql.UUID(as_uuid=True)), sa.Column("metadata_json", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), schema="plugins")
    op.create_table("secrets", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("plugin_key", sa.String(96), nullable=False), sa.Column("scope", sa.String(24), nullable=False, server_default="plugin"), sa.Column("scope_key", sa.String(160), nullable=False, server_default=""), sa.Column("secret_name", sa.String(120), nullable=False), sa.Column("ciphertext", sa.LargeBinary(), nullable=False), sa.Column("nonce", sa.LargeBinary(), nullable=False), sa.Column("key_version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_by_user_id", postgresql.UUID(as_uuid=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("plugin_key", "scope", "scope_key", "secret_name", name="uq_plugins_secret_scope"), schema="plugins")
    op.create_table("secret_audit", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("plugin_key", sa.String(96), nullable=False), sa.Column("secret_name", sa.String(120), nullable=False), sa.Column("action", sa.String(32), nullable=False), sa.Column("success", sa.Boolean(), nullable=False, server_default="true"), sa.Column("actor_user_id", postgresql.UUID(as_uuid=True)), sa.Column("metadata_json", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), schema="plugins")
    op.create_table("activation_state", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("plugin_key", sa.String(96), nullable=False), sa.Column("state", sa.String(24), nullable=False, server_default="stopped"), sa.Column("enabled", sa.Boolean(), nullable=False, server_default="false"), sa.Column("maintenance", sa.Boolean(), nullable=False, server_default="false"), sa.Column("restart_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("pid", sa.Integer()), sa.Column("last_heartbeat_at", sa.DateTime(timezone=True)), sa.Column("last_error", sa.Text()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("plugin_key", name="uq_plugins_activation_state_key"), schema="plugins")
    op.create_table("activation_history", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("plugin_key", sa.String(96), nullable=False), sa.Column("action", sa.String(32), nullable=False), sa.Column("previous_state", sa.String(24)), sa.Column("new_state", sa.String(24), nullable=False), sa.Column("actor_user_id", postgresql.UUID(as_uuid=True)), sa.Column("message", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), schema="plugins")
    op.create_table("package_history", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("plugin_key", sa.String(96), nullable=False), sa.Column("version", sa.String(40), nullable=False), sa.Column("previous_version", sa.String(40)), sa.Column("action", sa.String(24), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="success"), sa.Column("checksum_sha256", sa.String(64)), sa.Column("metadata_json", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("actor_user_id", postgresql.UUID(as_uuid=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), schema="plugins")
    for table in ("permissions","plugin_permissions","permission_audit","secrets","secret_audit","activation_state","activation_history","package_history"):
        op.execute(f"DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='shieldnet_backend') THEN GRANT SELECT,INSERT,UPDATE,DELETE ON plugins.{table} TO shieldnet_backend; END IF; END $$;")

def downgrade():
    for table in ("package_history","activation_history","activation_state","secret_audit","secrets","permission_audit","plugin_permissions","permissions"):
        op.drop_table(table, schema="plugins")
